<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cancionesporlista', 'doctrine');

/**
 * BaseCancionesporlista
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $loginpropietario
 * @property string $nombrelista
 * @property integer $idcancionlista
 * @property Listas $Listas
 * @property Listas $Listas_2
 * @property Canciones $Canciones
 * 
 * @method string            getLoginpropietario() Returns the current record's "loginpropietario" value
 * @method string            getNombrelista()      Returns the current record's "nombrelista" value
 * @method integer           getIdcancionlista()   Returns the current record's "idcancionlista" value
 * @method Listas            getListas()           Returns the current record's "Listas" value
 * @method Listas            getListas2()          Returns the current record's "Listas_2" value
 * @method Canciones         getCanciones()        Returns the current record's "Canciones" value
 * @method Cancionesporlista setLoginpropietario() Sets the current record's "loginpropietario" value
 * @method Cancionesporlista setNombrelista()      Sets the current record's "nombrelista" value
 * @method Cancionesporlista setIdcancionlista()   Sets the current record's "idcancionlista" value
 * @method Cancionesporlista setListas()           Sets the current record's "Listas" value
 * @method Cancionesporlista setListas2()          Sets the current record's "Listas_2" value
 * @method Cancionesporlista setCanciones()        Sets the current record's "Canciones" value
 * 
 * @package    MusicStore
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCancionesporlista extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cancionesporlista');
        $this->hasColumn('loginpropietario', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('nombrelista', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('idcancionlista', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Listas', array(
             'local' => 'nombrelista',
             'foreign' => 'nombrelistas'));

        $this->hasOne('Listas as Listas_2', array(
             'local' => 'loginpropietario',
             'foreign' => 'loginduenolista'));

        $this->hasOne('Canciones', array(
             'local' => 'idcancionlista',
             'foreign' => 'idcanciones'));
    }
}