<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Carrito', 'doctrine');

/**
 * BaseCarrito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcompra
 * @property string $logincomprador
 * @property integer $idcancioncomprada
 * @property date $fecha
 * @property float $precio
 * @property Usuarios $Usuarios
 * @property Disponibles $Disponibles
 * 
 * @method integer     getIdcompra()          Returns the current record's "idcompra" value
 * @method string      getLogincomprador()    Returns the current record's "logincomprador" value
 * @method integer     getIdcancioncomprada() Returns the current record's "idcancioncomprada" value
 * @method date        getFecha()             Returns the current record's "fecha" value
 * @method float       getPrecio()            Returns the current record's "precio" value
 * @method Usuarios    getUsuarios()          Returns the current record's "Usuarios" value
 * @method Disponibles getDisponibles()       Returns the current record's "Disponibles" value
 * @method Carrito     setIdcompra()          Sets the current record's "idcompra" value
 * @method Carrito     setLogincomprador()    Sets the current record's "logincomprador" value
 * @method Carrito     setIdcancioncomprada() Sets the current record's "idcancioncomprada" value
 * @method Carrito     setFecha()             Sets the current record's "fecha" value
 * @method Carrito     setPrecio()            Sets the current record's "precio" value
 * @method Carrito     setUsuarios()          Sets the current record's "Usuarios" value
 * @method Carrito     setDisponibles()       Sets the current record's "Disponibles" value
 * 
 * @package    MusicStore
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCarrito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('carrito');
        $this->hasColumn('idcompra', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('logincomprador', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('idcancioncomprada', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('precio', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuarios', array(
             'local' => 'logincomprador',
             'foreign' => 'login'));

        $this->hasOne('Disponibles', array(
             'local' => 'idcancioncomprada',
             'foreign' => 'iddisponibles'));
    }
}