<?php

/**
 * CancionesporlistaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CancionesporlistaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CancionesporlistaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cancionesporlista');
    }
}