<?php

/**
 * CancionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CancionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CancionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Canciones');
    }
}