<?php

/**
 * CancionesporusuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CancionesporusuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CancionesporusuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cancionesporusuario');
    }
}