<?php

/**
 * CarritoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CarritoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CarritoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Carrito');
    }
}