<?php

/**
 * CompartidasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompartidasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompartidasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Compartidas');
    }
}