<?php

/**
 * DisponiblesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DisponiblesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DisponiblesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Disponibles');
    }
}