<?php

/**
 * ListasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Listas');
    }
}