# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
buscarSucess:        
  layout:         layout_sn
indexSuccess:
    layout:       layout
recomendSuccess: 
    layout:       layout_sn
norecomendSuccess: 
    layout:       layout_sn
addSuccess:
  layout:         layout_sn