<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/28 22:48:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=MusicStore',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
