<?php
// auto-generated by sfViewConfigHandler
// date: 2012/12/05 10:43:46
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'buscarSucess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'indexSucess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'recomendSucess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'norecomendSucess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'buscarSucess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'layout_sn' ? false : 'layout_sn'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('main2.css', '', array ());
  $response->addJavascript('hideshow.js', '', array ());
  $response->addJavascript('jquery-1.5.2.min.js', '', array ());
  $response->addJavascript('jquery.equalHeight.js', '', array ());
  $response->addJavascript('jquery.tablesorter.min.js', '', array ());
  $response->addJavascript('audio-player.js', '', array ());
  $response->addJavascript('swfobject.js', '', array ());
}
else if ($templateName.$this->viewName == 'indexSucess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('main2.css', '', array ());
  $response->addJavascript('hideshow.js', '', array ());
  $response->addJavascript('jquery-1.5.2.min.js', '', array ());
  $response->addJavascript('jquery.equalHeight.js', '', array ());
  $response->addJavascript('jquery.tablesorter.min.js', '', array ());
  $response->addJavascript('audio-player.js', '', array ());
  $response->addJavascript('swfobject.js', '', array ());
}
else if ($templateName.$this->viewName == 'recomendSucess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'layout_sn' ? false : 'layout_sn'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('main2.css', '', array ());
  $response->addJavascript('hideshow.js', '', array ());
  $response->addJavascript('jquery-1.5.2.min.js', '', array ());
  $response->addJavascript('jquery.equalHeight.js', '', array ());
  $response->addJavascript('jquery.tablesorter.min.js', '', array ());
  $response->addJavascript('audio-player.js', '', array ());
  $response->addJavascript('swfobject.js', '', array ());
}
else if ($templateName.$this->viewName == 'norecomendSucess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'layout_sn' ? false : 'layout_sn'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('main2.css', '', array ());
  $response->addJavascript('hideshow.js', '', array ());
  $response->addJavascript('jquery-1.5.2.min.js', '', array ());
  $response->addJavascript('jquery.equalHeight.js', '', array ());
  $response->addJavascript('jquery.tablesorter.min.js', '', array ());
  $response->addJavascript('audio-player.js', '', array ());
  $response->addJavascript('swfobject.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('main2.css', '', array ());
  $response->addJavascript('hideshow.js', '', array ());
  $response->addJavascript('jquery-1.5.2.min.js', '', array ());
  $response->addJavascript('jquery.equalHeight.js', '', array ());
  $response->addJavascript('jquery.tablesorter.min.js', '', array ());
  $response->addJavascript('audio-player.js', '', array ());
  $response->addJavascript('swfobject.js', '', array ());
}

