<?php
// auto-generated by sfViewConfigHandler
// date: 2012/10/29 02:03:23
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('style.css', '', array ());
  $response->addStylesheet('grid.css', '', array ());
  $response->addStylesheet('ie.css', '', array ());
  $response->addStylesheet('prettyPhoto.css', '', array ());
  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addJavascript('html5.js', '', array ());
  $response->addJavascript('FF-cash.js', '', array ());
  $response->addJavascript('Vegur_400.font.js', '', array ());
  $response->addJavascript('Vegur_700.font.js', '', array ());
  $response->addJavascript('cufon-replace.js', '', array ());
  $response->addJavascript('cufon-yui.js', '', array ());
  $response->addJavascript('easyTooltip.js', '', array ());
  $response->addJavascript('hover-image.js', '', array ());
  $response->addJavascript('jquery-1.6.3.min.js', '', array ());
  $response->addJavascript('jquery.easing.1.3.js', '', array ());
  $response->addJavascript('jquery.galleriffic.js', '', array ());
  $response->addJavascript('jquery.opacityrollover.js', '', array ());
  $response->addJavascript('jquery.prettyPhoto.js', '', array ());
  $response->addJavascript('script.js', '', array ());
  $response->addJavascript('tms-0.3.js', '', array ());
  $response->addJavascript('tms_presets.js', '', array ());


